### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by Mayurifag** [BodyCount/vKappa#1]
Будет ли поддержка Firefox? В частности, будет ли когда-то расширение и для форка FF, Pale Moon? 

Спасибо, алсо, за проделанную работу, хотя в действии еще видеть не довелось.

**Comment by BodyCount** [comment]
Не разбирался в  API Firefox, все время было лень. Не могу с уверенностью ответить на этот вопрос.

**Comment by Mayurifag** [comment]
И все-таки, в крайней степени был бы признателен за подобную работу.
